dnj = {}

dnj.rq1 = 'lockpick' -- required item na cl_budky.lua
dnj.br1 = 50 -- chance na break

dnj.sg1 = 'screwdriver' -- required item na cl_znacky.lua
dnj.sg2 = 50 -- chance na break

dnj.cl = 20 * 60000 -- hodina

dnj.phx = {
    mdls = {
        "p_phonebox_01b_s",
        "prop_phonebox_04",
        "sf_prop_sf_phonebox_01b_s",
        "prop_phonebox_01c",
        "p_phonebox_02_s",
        "prop_phonebox_01a",
        "prop_phonebox_01b",
        "prop_phonebox_02",
        "prop_phonebox_03",
        "sf_prop_sf_phonebox_01b_straight",
        "hei_prop_carrier_phone_02"
    },
    mm = 50, -- min cash
    mx = 150, -- max cash
    skl = {'easy', 'easy', 'medium'}
}

dnj.mlx = {
    mdls = {
        "prop_news_disp_02a",
		"prop_news_disp_06a",
		"prop_news_disp_02c",
		"prop_news_disp_02d",
		"prop_news_disp_02b",
		"prop_news_disp_02e",
		"prop_news_disp_03a",
		"prop_news_disp_03b",
		"prop_news_disp_03c",
		"prop_news_disp_03d",
		"prop_news_disp_03e",
		"prop_news_disp_03f",
		"prop_news_disp_03g",
		"prop_news_disp_01a",
		"prop_news_disp_01b",
		"prop_news_disp_01c",
		"prop_news_disp_01d",
		"prop_news_disp_01e",
		"prop_news_disp_01f",
		"prop_news_disp_01g",
		"prop_postbox_01a",
        "2108567945",
        "-1940238623"
    },
    mm = 20, -- min cash
    mx = 80, -- max cash
    skl = {'easy', 'medium'}
}

dnj.sgnscrp = {
    skl = {'easy', 'easy', 'medium'},
    rwrw = { -- rewards
        { item = 'scrap', min = 1, max = 3 }, 
        { item = 'screw', min = 1, max = 3 }
    },
    mdls = {
        "prop_sign_road_01a",
        "prop_sign_road_02a",
        "prop_sign_road_03a",
        "prop_sign_road_03b",
        "prop_sign_road_03c",
        "prop_sign_road_04a",
        "prop_sign_road_04b",
        "prop_sign_road_04c",
        "prop_sign_road_04d",
        "prop_sign_road_04e",
        "prop_sign_road_05a",
        "prop_sign_road_05b",
        "prop_sign_road_05c",
        "prop_sign_road_05d",
        "prop_sign_road_05e",
        "prop_sign_road_05f",
        "prop_sign_road_05g",
        "prop_sign_road_06a",
        "prop_sign_road_06b",
        "prop_sign_road_06c",
        "prop_sign_road_06d",
        "prop_sign_road_06e",
        "prop_sign_road_06f",
        "prop_sign_road_07a",
        "prop_sign_road_07b",
        "prop_sign_road_08",
        "prop_sign_road_09",
        "prop_sign_road_10",
        "prop_sign_road_11",
        "prop_sign_road_12",
        "prop_sign_road_13",
        "prop_sign_road_14",
        "prop_sign_road_15a",
        "prop_sign_road_15b",
        "prop_sign_road_16a",
        "prop_sign_road_16b",
        "prop_sign_road_16c",
        "prop_sign_road_16d",
        "prop_sign_road_16e",
        "prop_sign_road_16f",
        "prop_sign_road_16g",
        "prop_sign_road_16h",
        "prop_sign_road_16i",
        "prop_sign_road_16j",
        "prop_sign_road_16k",
        "prop_sign_road_16l",
        "prop_sign_road_16m",
        "prop_sign_road_16n",
        "prop_sign_road_16o",
        "prop_sign_road_16p",
        "prop_sign_road_16q",
        "prop_sign_road_16r",
        "prop_sign_road_16s",
        "prop_sign_road_16t",
        "prop_sign_road_16u",
        "prop_sign_road_16v",
        "prop_sign_road_16w",
        "prop_sign_road_16x",
        "prop_sign_road_16y",
        "prop_sign_road_16z",
        "prop_sign_road_17",
        "prop_sign_road_18",
        "prop_sign_road_19",
        "prop_sign_road_20",
        "prop_sign_road_21",
        "prop_sign_road_22",
        "prop_sign_road_23",
        "prop_sign_road_24",
        "prop_sign_road_25",
        "prop_sign_road_26",
        "prop_sign_road_27",
        "prop_sign_road_28",
        "prop_sign_road_29",
        "prop_sign_road_30",
        "prop_sign_road_31",
        "prop_sign_road_32",
        "prop_sign_road_33",
        "prop_sign_road_34",
        "prop_sign_road_35",
        "prop_sign_road_36",
        "prop_sign_road_37",
        "prop_sign_road_38",
        "prop_sign_road_39",
        "prop_sign_road_40",
        "prop_sign_road_41",
        "prop_sign_road_42",
        "prop_sign_road_43",
        "prop_sign_road_44",
        "prop_sign_road_45",
        "prop_sign_road_46",
        "prop_sign_road_47",
        "prop_sign_road_48",
        "prop_sign_road_49",
        "prop_sign_road_50",
        "prop_sign_road_51",
        "prop_sign_road_52",
        "prop_sign_road_53",
        "prop_sign_road_54",
        "prop_sign_road_55",
        "prop_sign_road_56",
        "prop_sign_road_57",
        "prop_sign_road_58",
        "prop_sign_road_59",
        "prop_sign_road_60",
        "prop_sign_road_61",
        "prop_sign_road_62",
        "prop_sign_road_63",
        "prop_sign_road_64",
        "prop_sign_road_65",
        "prop_sign_road_66",
        "prop_sign_road_67",
        "prop_sign_road_68",
        "prop_sign_road_69",
        "prop_sign_road_70",
        "prop_sign_road_71",
        "prop_sign_road_72",
        "prop_sign_road_73",
        "prop_sign_road_74",
        "prop_sign_road_75",
        "prop_sign_road_76",
        "prop_sign_road_77",
        "prop_sign_road_78",
        "prop_sign_road_79",
        "prop_sign_road_80",
        "prop_sign_road_81",
        "prop_sign_road_82",
        "prop_sign_road_83",
        "prop_sign_road_84",
        "prop_sign_road_85",
        "prop_sign_road_86",
        "prop_sign_road_87",
        "prop_sign_road_88",
        "prop_sign_road_89",
        "prop_sign_road_90",
        "prop_sign_road_91",
        "prop_sign_road_92",
        "prop_sign_road_93",
        "prop_sign_road_94",
        "prop_sign_road_95",
        "prop_sign_road_96",
        "prop_sign_road_97",
        "prop_sign_road_98",
        "prop_sign_road_99",
        "prop_sign_road_100",
        "prop_sign_freewayentrance",
        "prop_sign_freewayexit",
        "prop_sign_interstate_01",
        "prop_sign_interstate_02",
        "prop_sign_interstate_03",
        "prop_sign_interstate_04",
        "prop_sign_interstate_05",
        "prop_sign_interstate_06",
        "prop_sign_interstate_07",
        "prop_sign_interstate_08",
        "prop_sign_interstate_09",
        "prop_sign_interstate_10",
        "prop_sign_interstate_11",
        "prop_sign_interstate_12",
        "prop_sign_interstate_13",
        "prop_sign_interstate_14",
        "prop_sign_interstate_15",
        "prop_sign_interstate_16",
        "prop_sign_interstate_17",
        "prop_sign_interstate_18",
        "prop_sign_interstate_19",
        "prop_sign_interstate_20",
        "prop_sign_interstate_21",
        "prop_sign_interstate_22",
        "prop_sign_interstate_23",
        "prop_sign_interstate_24",
        "prop_sign_interstate_25",
        "prop_sign_interstate_26",
        "prop_sign_interstate_27",
        "prop_sign_interstate_28",
        "prop_sign_interstate_29",
        "prop_sign_interstate_30",
        "-97646180",
        "1369811908",
        "1131941737",
        "-1393761711"
    }
}
